name: build
on: [ push,  pull_request, workflow_dispatch ]
jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      checks: write
      pull-requests: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -Dno-format -Ddetailed-coverage verify

      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v3
        with:
          ref: badges
          path: badges

      - name: Generate Overall Jacoco Badge
        id: jacoco-overall
        # v2.8.0 introduces an automatic step summary that can't be turned off
        uses: cicirello/jacoco-badge-generator@v2.7.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: 'PSP031-jacoco-report/target/site/jacoco-aggregate/jacoco.csv'
          badges-directory: badges
          coverage-badge-filename: jacoco-overall.svg
          branches-badge-filename: branches-overall.svg

      - name: Generate Model Jacoco Badge
        id: jacoco-model
        # v2.8.0 introduces an automatic step summary that can't be turned off
        uses: cicirello/jacoco-badge-generator@v2.7.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: 'PSP031-jacoco-report/target/site/jacoco-aggregate-model/jacoco.csv'
          badges-directory: badges
          coverage-badge-filename: jacoco-model.svg
          branches-badge-filename: branches-model.svg

      - name: Generate Controller Jacoco Badge
        id: jacoco-controller
        # v2.8.0 introduces an automatic step summary that can't be turned off
        uses: cicirello/jacoco-badge-generator@v2.7.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: 'PSP031-jacoco-report/target/site/jacoco-aggregate-controller/jacoco.csv'
          badges-directory: badges
          coverage-badge-filename: jacoco-controller.svg
          branches-badge-filename: branches-controller.svg

      - name: Commit and Push Badges
        if: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
        continue-on-error: true
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add *.svg
            git commit -m "Autogenerated JaCoCo coverage badge" *.svg
            git push
          fi

      - name: Generate Coverage Summary
        id: jacoco-summary
        env:
          JACOCO_MODEL_COVERAGE: ${{ steps.jacoco-model.outputs.coverage }}
          JACOCO_MODEL_BRANCHES: ${{ steps.jacoco-model.outputs.branches }}
          JACOCO_CONTROLLER_COVERAGE: ${{ steps.jacoco-controller.outputs.coverage }}
          JACOCO_CONTROLLER_BRANCHES: ${{ steps.jacoco-controller.outputs.branches }}
          JACOCO_OVERALL_COVERAGE: ${{ steps.jacoco-overall.outputs.coverage }}
          JACOCO_OVERALL_BRANCHES: ${{ steps.jacoco-overall.outputs.branches }}
        run: |
          JACOCO_SUMMARY=$(cat <<EOF
          ## JaCoCo Coverage Report
          |            | Instructions | Branches |
          |------------|:------------:|---------:|
          $(printf "| Model      | %.2f%%      | %.2f%%  |\n" "$(echo "100 * $JACOCO_MODEL_COVERAGE"      | bc)" "$(echo "100 * $JACOCO_MODEL_BRANCHES"      | bc)")
          $(printf "| Controller | %.2f%%      | %.2f%%  |\n" "$(echo "100 * $JACOCO_CONTROLLER_COVERAGE" | bc)" "$(echo "100 * $JACOCO_CONTROLLER_BRANCHES" | bc)")
          $(printf "| Overall    | %.2f%%      | %.2f%%  |\n" "$(echo "100 * $JACOCO_OVERALL_COVERAGE"    | bc)" "$(echo "100 * $JACOCO_OVERALL_BRANCHES"    | bc)")
          EOF
          )
          
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "summary<<$EOF" >> $GITHUB_OUTPUT
          echo "$JACOCO_SUMMARY" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
          
          JACOCO_SUMMARY="${JACOCO_SUMMARY//$'\n'/'\n'}"
          echo "escaped-summary<<$EOF" >> $GITHUB_OUTPUT
          echo "$JACOCO_SUMMARY" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Add Coverage Job Summary
        env:
          JACOCO_SUMMARY: ${{ steps.jacoco-summary.outputs.summary }}
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          $JACOCO_SUMMARY
          EOF

      - name: Add Coverage Check Run
        uses: LouisBrunner/checks-action@v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Coverage
          conclusion: success
          output: >
            {"summary":"${{ steps.jacoco-summary.outputs.escaped-summary }}"}

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/target/surefire-reports/TEST-*.xml'

      - name: Upload Jacoco Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: 'PSP031-jacoco-report/target/site/jacoco-aggregate/'
